name: Package & Distribute

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Package for ${{ matrix.platform-name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform-name: macOS
            make-cmd: npm run make:mac
            artifact-name: Vault-macOS
          - os: windows-latest
            platform-name: Windows
            make-cmd: npm run make:win
            artifact-name: Vault-Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run test suite
        run: npm test

      - name: Build and Package Distributables
        run: ${{ matrix.make-cmd }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: out/make/**/*
          if-no-files-found: error
